#!/bin/bash
# License: GPLv2
# Author: "Simon Müller" <git@simon-mueller.de>
# Dependencies: ffmpeg
#
# Script to shrink the filesize of a video to < 8MB
# in order to upload it into Discord. Unfortunately this
# closed source application will only let upload files below this size.
#
# You can change the threshold in kb for the filesize here.
THRESHOLD=10000
# You can change the factor the quality will decrease here,
# results in faster results/fewer rounds but may decrease quality too much
GROWFACTOR=1

PROCESSED=0

# stop on ctrl+c
trap "echo 'SIGINT received, aborting...' && exit" INT

if [[ -z $@ ]]; then
	echo -e "No argument given!\nUsage: shrink4discord <videofile> [quality, default=28]"
	exit 255
fi

if [[ "$1" == "last" ]]; then
	INFILE=$(ls -Art | tail -n 1)
else
	INFILE="${1}"
fi
OUTFILE="${INFILE%.*}_.${INFILE##*.}"
QUAL=${2}

if [[ -z ${QUAL} ]]; then
	QUAL=28
fi

VIDSIZE=$(du -s "${INFILE}"|awk '{ print $1 }')
VIDINFO=$(file -sL "${INFILE}")
echo "$VIDSIZE - ${VIDINFO}"

while [[ "${VIDSIZE}" -gt "${THRESHOLD}" ]]; do
	echo "Shrinking ${VIDSIZE} KB file with ffmpeg (quality: ${QUAL})..."
	ffmpeg -loglevel "warning" -y -i "${INFILE}" -vcodec libx264 -crf ${QUAL} "${OUTFILE}"
	VIDSIZE=$(du -s "${OUTFILE}"|awk '{ print $1 }')
	QUAL=$(($QUAL+$GROWFACTOR))
	PROCESSED=1
done

if [[ $PROCESSED -eq 1 ]]; then
	echo "Finished processing ${INFILE}, final size: ${VIDSIZE} KB. Removing original file..."
	rm -v "${INFILE}"
	exit 0
fi
echo "File smaller than $THRESHOLD KB, exiting!"
exit 1
